### ISSUE TITLE
Device support request: Hori Real Arcade Pro V Hayabusa for Xbox One

### ISSUE THREAD

**Issue by Vewlix16** [OOPMan/XBOFS.win#19]
[device and configuration descriptor.txt](https://github.com/OOPMan/XBOFS.win/files/6370424/device.and.configuration.descriptor.txt)

**Comment by OOPMan** [comment]
@Vewlix16 Please find attached a ZaDig preset file to test. Instructions:

1. Download the new preset file: [hori_hayabusa_rap_pro_v.cfg.txt](https://github.com/OOPMan/XBOFS.win/files/6371069/hori_hayabusa_rap_pro_v.cfg.txt)
2. Rename the file from `hori_hayabusa_rap_pro_v.cfg.txt` to `hori_hayabusa_rap_pro_v.cfg` (I had to add the `.txt` extension due to a restriction from GitHub)
3. Place the file in your `XBOFS.win\za_presets` folder
4. Proceed to follow the [ZaDig Driver](https://xbofs.win/zadig.html) installation guide as usual, using the new preset file at step 5 instead of the either of the existing ones.
5. Reboot your system
6. Start XBOFS.win
7. Plug in your device. If the preset is working a new tab should appear in the window labelled `Stick 1`
8. Try playing a game that uses the stick

**Comment by OOPMan** [comment]
User reports the new preset does not function with device. Closing this ticket for now unless I happen to come across a Rap Pro V.
