### ISSUE TITLE
Stuck Scanning for supported controllers

### ISSUE THREAD

**Issue by shankera** [OOPMan/XBOFS.win#44]
The status never changes from `Scanning for supported controllers...`. I've tried uninstalling and reinstalling, and various combinations of plugging in the fight stick and starting the application to try and get it to resolve, but I haven't been able to influence it. Let me know what 

Application:
![image](https://user-images.githubusercontent.com/5796193/216895065-8809a480-37fb-44c9-b3d0-282774b8f4cc.png)

Device manager:
![image](https://user-images.githubusercontent.com/5796193/216895105-0a8f6db1-c02f-434f-a2ae-471d3d04efbf.png)

**Comment by OOPMan** [comment]
@shankera Have you installed the Driver using the Driver Manager tool?

**Comment by shankera** [comment]
I believe so, I went through all the steps as outlined and ran into no unexpected errors. How can I confirm this?

**Comment by OOPMan** [comment]
@shankera I ask because the second screenshot indicates the Driver was not installed and it is still using the default XBOX GIP (Game Input Protocol) driver.

I'd recommend following the instructions on the page https://xbofs.win/troubleshooting.html, specifically the section labelled `When I try to install the WinUSB Driver using the Driver Manager I get libwdi Result Code -11`

**Comment by shankera** [comment]
The troubleshooting steps solved my problems - thank you
